import type { Metadata } from 'next';
import './globals.css';
import 'bulma/css/bulma.css';
export const metadata: Metadata = {
  title: 'Next',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>{children}</body>
    </html>
  );
}
