import type { Metadata } from 'next';
import './globals.css';
import 'bulma/css/bulma.css';
import { Menu } from '@/components/menu';
export const metadata: Metadata = {
  title: 'Next',
  description: 'Generated by create next app',
};

export default function RootLayout(props: any) {
  return (
    <html lang="pt-br">
      <body className="app">
        <section className="main-content columns is-fullheight">
          <Menu />
          <div className="container column is-10">
            <div className="section">
              <div className="card">
                <div className="card-header">
                  <p className="card-header-title">{props.titulo}</p>
                </div>
                <div className="card-content">
                  <div className="content">{props.children}</div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </body>
    </html>
  );
}
